### ISSUE TITLE
Performance issues in react-native

### ISSUE THREAD

**Issue by mtford90** [evgenyrodionov/redux-logger#32] opened 2015-09-24 12:03 UTC
Hey, 

Just to let ya know - we've been seeing really poor performance with redux-logger enabled when used with react-native on iOS - even on new iPhone devices. Use of the logger would cause the app to freeze for seconds at a time.

I've attached a screenshot from xcode instruments which is what led us to disabling redux-logger:

<img width="1221" alt="screen shot 2015-09-22 at 13 17 10" src="https://cloud.githubusercontent.com/assets/1734057/10072829/87602eac-62bc-11e5-8d12-3252763d822f.png">

Not entirely sure whether this is redux-logger's fault entirely, but may be worth looking into

**Comment by gaearon** [comment] 2015-09-24 13:03
If `console.log`s are slow this seems like something better addressed in RN itself.

**Comment by theaqua** [comment] 2015-09-24 16:20
`redux-logger` just calls `console.log()` in basic variant. Do you pass any options to `createLogger`?

**Comment by mtford90** [comment] 2015-09-24 18:07
@theaqua we do not.

I haven't noticed any performance issues with use of our own logging so when the problems ceased after removal of redux-logger I just assumed it was at fault :p. The weird thing is that redux-logger doesn't really seem to log too often - just on actions etc so I have no idea why performance would be so badly affected.

If I get a chance it's prob worth doing some profiling with the chrome dev tools or equivalent to see where the time is being spent within the javascript as opposed to the native code.

**Comment by DeepAnchor** [comment] 2015-11-13 01:56
Besides being slow, did everything else in your app work normally @mtford90 ? I added `redux-logger` into my middleware chain and stuff began failing silently. Reducers stopped getting called, actions stopped being dispatched, etc. Removed `redux-logger` and everything went back to normal.

**Comment by tomauty** [comment] 2015-12-07 20:13
Yeah, I just discovered that this was the cause of our performance issues. Would highly recommend mentioning in the documentation that this should be disabled for production builds.

**Comment by gaearon** [comment] 2015-12-07 21:00
It definitely should! (Just like DevTools)

**Comment by tomauty** [comment] 2015-12-07 21:03
Would be curious to see if it has anything to do with the formatting functions (e.g. colors) involved in the logging. The only time this affected my application was when I was _not_ debugging with chrome. When chrome's logger was used, everything was mostly smooth.

**Comment by tomauty** [comment] 2015-12-07 21:12
Having removed the formatters, and replaced with pure console.log functions, I'm convinced it's the formatting of the statements that causes the hang. Currently investigating how to differentiate between formattable window instances and not, but for now this is what I've done as a workaround:

```javascript
const args = (global.__DEV__) ? [thunk, api, logger] : [thunk, api];
const createStoreWithMiddleware = applyMiddleware(...args)(createStore);
```

**Comment by tomauty** [comment] 2015-12-07 21:16
Actually, reading through releases, it looks like `colors: false` as an option might suffice. Sorry for the comment-spam. Will try and report back if no one else does before me.

**Comment by gaearon** [comment] 2015-12-08 00:47
You're still (quite probably) wasting memory because you're logging state objects so they (probably?) can't be GC'ed. So don't log in prod.

**Comment by tomauty** [comment] 2015-12-08 00:49
Oh for sure, can't see why one would want to log in a production react native app anyway.

**Comment by theaqua** [comment] 2015-12-16 23:54
I close this issue because for ~3 months we're still don't know what is causes problem and issue with that title scares newcomers :)
If anyone have steps to reproduce and it's precisely our problem, please file a new issue.

**Comment by fabiosussetto** [comment] 2016-03-31 09:43
I really think this issue should be mentioned clearly in the docs. I run into the same problem and it took me a while to understand the terrible performance issues I was getting on iOS where just caused by redux-logger. I don't know exactly why this happens (I guess it's got to do with the GC not being able to remove the states as console.log works by reference?), but it's definitely happening.

**Comment by theaqua** [comment] 2016-03-31 09:47
@fabiosussetto lol I can't mention it in docs while nobody doesn't understand why it happens. See it as a newcomer: "hey, we have the nice library with a bunch of `console.log`s, but we (2 people of 173,301 downloads) stuck with one problem of performance". I definitely will not use that library.

**Comment by fabiosussetto** [comment] 2016-03-31 10:17
@theaqua probably I didn't make my point clear enough. There's a bunch of places where people mention that using console.log causes very noticeable performance issues in react native (e.g. https://github.com/aksonov/react-native-router-flux/issues/199#issuecomment-190474938)

> hey, we have the nice library with a bunch of console.logs, but we stuck with one problem of performance". I definitely will not use that library

I don't really think it's a good idea to "hide" potential issues just so that people don't get scared by them, it's not really transparent.

IMO a "Known issues" section could be easily added to the readme, mentioning something like: 
"We are aware some people reported performance issues using console.log (and thus redux-logger) in React Native. If you get these issues, please consider removing redux-logger in production".

I don't see how this can harm this project, all the best project have a "Known issues" section where potential problems are mentioned while being investigated/fixed. 
For me it was a big waste of time realising that the performance issues I was getting where just because of this. I would have been very happy to be aware of this potential problem from the beginning.

Then it's obviously up to you.

**Comment by calebmer** [comment] 2016-07-13 19:29
As a note, `redux-logger` is slowing down React Native for me too.

**Comment by lakhman** [comment] 2016-10-13 17:35
Yes this tripped me up also, very annoying. The following snippet should be added to the docs as the default configuration.

From: slava-sh https://github.com/evgenyrodionov/redux-logger/issues/6

```
const middleware = [
  ... other middleware ...
  __DEV__ && logger,
].filter(Boolean);
const createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
```

If building for an iOS device, in xCode, click the `Run` button whilst pressing `ALT` to change the build scheme (and toggle to release).

This significantly slowed down the performance of a simple app, simply disabling it fixed everything.

👍  Update Docs

**Comment by evgenyrodionov** [comment] 2016-10-13 21:04
Reopened and mentioned in docs. I agree we need fix this.

**Comment by tezqa** [comment] 2016-10-29 13:15
Hello,
I have encountered a severe slow down in my app too, especially because my state contains a lot of data. Moreover, Xcode's console outputs all state's changes and this is exactly when slow downs  occur.
If i force the use of my store.prod.js instead of .dev.js, everything works fine.

**Comment by lakhman** [comment] 2016-10-29 13:29
I'd also like to note that using `console.log()` (accidently in a release app, for example) will significantly slow down performance (this is especially true on android).

I had a bug where a `console.log` statement (in a release build - with no redux logger) caused slow-animations and slow-responsive touch behaviour when using the `Navigator` component (on android), It was due to the `console.log` statements - removing them all fixed everything.

This is noted in the official docs here (Keep it in mind if you're new to React Native - _like me_):

https://facebook.github.io/react-native/docs/performance.html#console-log-statements

I tried using [babel-plugin-transform-remove-console](https://www.npmjs.com/package/babel-plugin-transform-remove-console), but this doesn't currently work with RN, there's an open issue here:

https://github.com/facebook/react-native/issues/10412

It seems, for now, remove/uncomment all `console.log` statements manually (and also disable the  redux-logger dev mode in release builds as noted above).

Hope this helps.

**Comment by tezqa** [comment] 2016-10-30 09:26
I have also notice that console.log (and console.**whatever**) could slow down your app.

A great alternative (instead of using another weird babel plugin) is to wrap console into you own module:

`if (!__DEV__) {
  console.log =
  console.info =
  console.error =
  console.warn =
  console.debug =
  console.trace = () => {};
}

export function log() {
  _d('log', arguments);
}

export function info() {
  _d('info', arguments);
}

export function warn() {
  _d('warn', arguments);
}

export function error() {
  _d('error', arguments);
}

export function debug() {
  _d('debug', arguments);
}

export function trace() {
  _d('trace', arguments);
}

function _d(type, args) {
  if (!__DEV__) return;
  if (args[0]) {
    args[0] = _getHeader() + args[0];
  }
  Function.apply.call(console[type], console, args);
}

function _getHeader() {
  var date = new Date();

  var d = date.getDay();
  if (d.toString().length == 1)
    d = '0' + d;

  var m = date.getMonth() + 1;
  if (m.toString().length == 1)
    m = '0' + m;

  var y = date.getFullYear();

  var h = date.getHours();
  if (h.toString().length == 1)
    h = '0' + h;

  var mn = date.getMinutes();
  if (mn.toString().length == 1)
    mn = '0' + mn;

  var s = date.getSeconds();
  if (s.toString().length == 1)
    s = '0' + s;

  var ms = date.getMilliseconds();
  var time = d + '/' + m + '/' + y + ' ' + h + ':' + mn + ':' + s + ' ' + ms;
  return '[YOUR_APP_NAME ' + time + '] ';
}`

**Comment by evgenyrodionov** [comment] 2016-10-30 16:04
By the way, you can pass own implementation of console in `options.console`. For example,
```js
const console = {
  log: () => {
    // your code
  },
  group: () => {
    // your code
  },
  // etc
};

const logger = createLogger({
  console: console,
});
```

**Comment by xwartz** [comment] 2016-11-11 02:39
How about [predicate func](https://github.com/evgenyrodionov/redux-logger#predicate--getstate-function-action-object--boolean)  option.

```js
const logger = createLogger({
  predicate: () => isDebugging,
  collapsed: true,
  duration: true,
 .....
})
```

**Comment by sibelius** [comment] 2017-01-09 12:27
can we close this?

**Comment by grushetsky** [comment] 2017-01-13 22:09
@sibelius, not sure yet. I didn't manage to analyze the problem. Do you have any feedback?

**Comment by sibelius** [comment] 2017-01-14 01:08
This is not a problem of redux-logger, it is a problem with console.log being slow on react native

**Comment by slorber** [comment] 2017-11-17 15:22
For those interested, here is a setting that works for me and still permits me to dev on Android:

```javascript
const isVerboseLoggingPlatform = Platform.OS === 'android';



  if (__DEV__) {
    middleware.push(
      createLogger({
        stateTransformer: state => {
          return isVerboseLoggingPlatform ? state : 'state';
        },
      }),
    );
  }
```

I suspect shipping state objects from phone/emulator to xcode requires some expensive serialization, not much we can do about it imho

**Comment by xotahal** [comment] 2018-03-01 22:45
I've run into this problem as well. It's not a problem with redux-logger itself. It's a problem with `console.log` as it was already mentioned. Anyway I've done a workaround for this. So just sharing the ideas.

There are 3 environments you can run your React Native app:
1. Production
2. Debug remotely
3. Debug (without chrome)

## Production
You definitely need to switch the redux-logger off (for example):
```js
const IS_PRODUCTION = process.env.NODE_ENV === 'production'

  const middlewares = [
      !IS_PRODUCTION &&
      createLogger({
        ....
      }),
  ]

  // remove non function middlewares
  middlewares.filter(middleware => _.isFunction(middleware))
```

## Debug remotely
The `IS_PRODUCTION` will be set to false. It means the redux-logger will be pushed to middlewares. In this case it works like Andrew Goodale said in [this thread](https://discuss.reactjs.org/t/react-native-runs-slow-on-ios-device-when-remote-debugger-is-off/6582)

> It's because when you run with remote debugging, the JavaScript code is executed inside Chrome's V8 engine. That is able to do various optimizations with JIT compiling. When running without debugging, JavaScript is executed by iOS's JavaScriptCore, which cannot JIT-compile JavaScript. There are also differences in performance between the two engines. For example, I noticed that mutating Date objects is slower in JavaScriptCore than V8.

**So we can leave as it is, because everything works smoothly**

## Debug (without chrome)
**The problem was with this case for me**. Everything went really slowly. And I don't really want the redux-logger in this case, because the JS runs on Device/Emulator without chrome/react-devtools. So I added this condition:
```js
const { pathname } = window.location || {}
const IS_RUNNING_IN_CHROME = pathname && pathname.indexOf('debugger-ui')
const IS_PRODUCTION = process.env.NODE_ENV === 'production'

  const middlewares = [
      IS_RUNNING_IN_CHROME && !IS_PRODUCTION &&
      createLogger({
        ....
      }),
  ]

  // remove non function middlewares
  middlewares.filter(middleware => _.isFunction(middleware))
```

If anybody knows there is a better way how to check that the chrome is running - tell me please :)

**Comment by grushetsky** [comment] 2018-03-11 09:49
@xotahal, thanks for sharing your experience!

**Closed by grushetsky** 2018-03-11 09:49 UTC
Labels: help wanted

**Comment by maartenvandillen** [comment] 2021-07-14 12:21
> By the way, you can pass own implementation of console in `options.console`. For example,
> 
> ```js
> const console = {
>   log: () => {
>     // your code
>   },
>   group: () => {
>     // your code
>   },
>   // etc
> };
> 
> const logger = createLogger({
>   console: console,
> });
> ```

yes this worked for me to prevent VS Code debug console to stop working:

```
  const logger = createLogger({
    console: { log: line => console.log(line) }
  });
```

It may be a bit over simplified and I don't see the pretty colors anymore, but solved my problem
